### ISSUE TITLE
Create self-contained plugin distributions on every release 

### ISSUE THREAD

**Issue by kasparsd** [xwp/site-performance-tracker#16]
Currently we only support installation through Composer, see #11. 

We need to add a build step that runs only on tags that creates a plugin distribution ZIP that contains all the dependencies. Also fixes #14 and #15.

**Comment by mehigh** [comment]
Adding this to .github/workflows/release.yml
needs configuring with the details correctly according to the specifics for this project:

```
on:
  push:
    tags: # Sequence of patterns matched against refs/tags
    - '**' # Do the build for any tagged releases.

name: Release Workflow

jobs:
  build:
    name: Plugin Release
    runs-on: ubuntu-latest
    env:
      slug: xcurrent
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        id: release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload ZIP
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.slug }}.zip
          asset_name: ${{ env.slug }}.zip
          asset_content_type: application/zip
```
